/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.gvc.telas;

import br.com.gvc.dal.ModuloConexao;
import java.sql.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.JTable;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Pedro
 */
public class TelaInternaVendaData extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    private static TelaInternaVendaData telaInternaVendaData;

    public static TelaInternaVendaData getInstancia() {
        if (telaInternaVendaData == null) {
            telaInternaVendaData = new TelaInternaVendaData();
        }
        return telaInternaVendaData;

    }

    public TelaInternaVendaData() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    private void retornaVendaData() {

        Date data1 = d1.getDate();
        Date data2 = d2.getDate();
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

        String data1Formatada = formatador.format(data1);
        String data2Formatada = formatador.format(data2);

        String sql = "select id_venda as ID, descricao as Descrição, preco_m2 as ValorMetro, "
                + "preco_unit as ValorUnit, quantidade as Qtd, preco_total as ValorTotal, pago as Pago,"
                + "dt_emissao as DtEmissão, id_cliente as Cliente from tb_venda where date(dt_emissao) "
                + "between ? and ?";

        try {
            if (data1Formatada.equals("") || data2Formatada.equals("")) {
                JOptionPane.showMessageDialog(null, "Selecione as datas!");
            } else if (data1Formatada.equals(data2Formatada)) {
                JOptionPane.showMessageDialog(null, "As datas não podem ser iguais!");
            } else {
                ps = conexao.prepareStatement(sql);
                ps.setString(1, data1Formatada);
                ps.setString(2, data2Formatada);
                rs = ps.executeQuery();

                tbl_vendas.setModel(DbUtils.resultSetToTableModel(rs));
                DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
                rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
                for(int i = 2; i <=5; i++){
                    tbl_vendas.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void imprimir() {

        Date data1 = d1.getDate();
        Date data2 = d2.getDate();
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

        String data1Formatada = formatador.format(data1);
        String data2Formatada = formatador.format(data2);

        Map p = new HashMap();
        p.put("data_1", data1Formatada);
        p.put("data_2", data2Formatada);
        JasperReport relatorio;
        JasperPrint impressao;
        try {
            relatorio = JasperCompileManager.compileReport(new File("").getAbsolutePath() + "/rel/rlVendaData.jrxml");
            impressao = JasperFillManager.fillReport(relatorio, p, conexao);
            JasperViewer view = new JasperViewer(impressao, false);
            view.setTitle("RLVData");
            view.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_tipo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vendas = new javax.swing.JTable();
        icon = new javax.swing.JLabel();
        d1 = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        d2 = new com.toedter.calendar.JCalendar();

        setBorder(null);
        setClosable(true);
        setForeground(new java.awt.Color(240, 240, 240));
        setTitle("Vendas por Data");
        setFrameIcon(null);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(800, 690));
        setVisible(false);

        tbl_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "ValorMetro", "ValorUnit", "Qtd", "ValorTotal", "Pago", "DtEmissão", "Cliente"
            }
        ));
        tbl_vendas.setColumnSelectionAllowed(true);
        tbl_vendas.getTableHeader().setReorderingAllowed(false);
        tbl_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_vendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_vendas);
        tbl_vendas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gvcsystem/img/gvc_system_logo_login.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("De:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Até:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Selecione um intervalo de data");

        btn_imprimir.setBackground(new java.awt.Color(230, 230, 230));
        btn_imprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_imprimir.setForeground(new java.awt.Color(0, 102, 102));
        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gvcsystem/img/imprimir.png"))); // NOI18N
        btn_imprimir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(230, 230, 230));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gvcsystem/img/buscar.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(icon)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBounds(0, 0, 800, 690);
    }// </editor-fold>//GEN-END:initComponents


    private void tbl_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_vendasMouseClicked

    }//GEN-LAST:event_tbl_vendasMouseClicked

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar o Relatório de Vendas?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            imprimir();
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        retornaVendaData();
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_tipo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_imprimir;
    private com.toedter.calendar.JCalendar d1;
    private com.toedter.calendar.JCalendar d2;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_vendas;
    // End of variables declaration//GEN-END:variables
}
